---
# Always use '#. ' before the actual title, for sorting purposes
- title: 1. Getting started
  apps:
  - robot_configurator
  - expression_configurator
  - preferences
  - circumplex

- title: 2. Ready-to-use apps
  apps:
  - circumplex
  - sliders
  - social_script
  - sounds
  - touch_graph
  - blockly
  - lua_scripting

- title: 3. Community apps
  apps:
  - social_response
  - app_template
  - cockpit
