audio:
  master_volume: 50
  tts_engine: pico
  tts_gender: f
  tts_language: en
behaviour:
  blink: true
  caffeine: 0
  enabled: true
  gaze: true
general:
  robot_name: robot
  startup_app: --None--
security:
  password: opsoro123
wireless:
  channel: 6
  password: RobotOpsoro
  ssid: OPSORO-NMCT
